name: Test

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "**.go"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/test.yaml"
      - "go.mod"
      - "go.sum"
      - "**.go"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ["1.18", "1.19"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go_version }}"
          cache: true

      - run: go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out -count=1 ./...

      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
